---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role credentials
# 
# Overview:
# 
#
# Dependencies:
#
# 
# Example play:
#
#

- name: add gunicorn configuration file
  template:
    src: edx/app/credentials/credentials_gunicorn.py.j2
    dest: "{{ credentials_home }}/credentials_gunicorn.py"
  sudo_user: "{{ credentials_user }}"
  tags:
    - install
    - install:configuration

- name: build virtualenv
  command: "virtualenv {{ credentials_venv_dir }}"
  args:
    creates: "{{ credentials_venv_dir }}/bin/pip"
  sudo_user: "{{ credentials_user }}"
  environment: "{{ credentials_environment }}"
  tags:
    - install
    - install:app-requirements

- name: install application requirements
  command: make prod-requirements
  args:
    chdir: "{{ credentials_code_dir }}"
  sudo_user: "{{ credentials_user }}"
  environment: "{{ credentials_environment }}"
  tags:
    - install
    - install:app-requirements

- name: install development requirements
  command: make requirements
  args:
    chdir: "{{ credentials_code_dir }}"
  sudo_user: "{{ credentials_user }}"
  environment: "{{ credentials_environment }}"
  tags:
    - devstack
    - devstack:install

- name: create nodeenv
  shell: >
    creates={{ credentials_nodeenv_dir }}
    {{ credentials_venv_dir }}/bin/nodeenv {{ credentials_nodeenv_dir }} --prebuilt
  sudo_user: "{{ credentials_user }}"

- name: install node dependencies
  npm: executable={{ credentials_nodeenv_bin }}/npm path={{ credentials_code_dir }} production=yes
  sudo_user: "{{ credentials_user }}"

- name: install bower dependencies
  shell: >
    chdir={{ credentials_code_dir }}
    . {{ credentials_nodeenv_bin }}/activate && {{ credentials_node_bin }}/bower install --production --config.interactive=false
  sudo_user: "{{ credentials_user }}"

- name: wait for database
  wait_for:
    host: "{{ CREDENTIALS_DATABASES.default.HOST }}"
    port: "{{ CREDENTIALS_DATABASES.default.PORT }}"
    delay: 2
  tags:
    - devstack
    - devstack:migrate

- name: create databases
  mysql_db:
    login_host: "{{ CREDENTIALS_DATABASES.default.HOST }}"
    login_user: "{{ CREDENTIALS_DB_ADMIN_USER }}"
    login_password: "{{ CREDENTIALS_DB_ADMIN_PASSWORD }}"
    db: "{{ CREDENTIALS_DEFAULT_DB_NAME }}"
    state: present
    encoding: utf8
  tags:
    - devstack
    - devstack:migrate

- name: create database users
  mysql_user:
    login_host: "{{ CREDENTIALS_DATABASES.default.HOST }}"
    login_user: "{{ CREDENTIALS_DB_ADMIN_USER }}"
    login_password: "{{ CREDENTIALS_DB_ADMIN_PASSWORD }}"
    name: "{{ item.name }}"
    host: "%"
    password: "{{ item.password }}"
    priv: "{{ CREDENTIALS_DEFAULT_DB_NAME }}.*:ALL"
  with_items:
    - name: "{{ CREDENTIALS_DATABASES.default.USER }}"
      password: "{{ CREDENTIALS_DATABASES.default.PASSWORD }}"
    - name: "{{ COMMON_MYSQL_MIGRATE_USER }}"
      password: "{{ COMMON_MYSQL_MIGRATE_PASS }}"
  tags:
    - devstack
    - devstack:migrate

- name: migrate database
  command: make migrate
  args:
    chdir: "{{ credentials_code_dir }}"
  sudo_user: "{{ credentials_user }}"
  environment: "{{ credentials_migration_environment }}"
  when: migrate_db is defined and migrate_db|lower == "yes"
  tags:
    - migrate
    - migrate:db
    - devstack
    - devstack:migrate

- name: write out the supervisor wrapper
  template:
    src: "edx/app/credentials/credentials.sh.j2"
    dest: "{{ credentials_home }}/{{ credentials_service_name }}.sh"
    mode: 0650
    owner: "{{ supervisor_user }}"
    group: "{{ common_web_user }}"
  tags:
    - install
    - install:configuration

- name: write supervisord config
  template:
    src: "edx/app/supervisor/conf.d.available/credentials.conf.j2"
    dest: "{{ supervisor_available_dir }}/{{ credentials_service_name }}.conf"
    owner: "{{ supervisor_user }}"
    group: "{{ common_web_user }}"
    mode: 0644
  tags:
    - install
    - install:configuration

- name: write devstack script
  template:
    src: "edx/app/credentials/devstack.sh.j2"
    dest: "{{ credentials_home }}/devstack.sh"
    owner: "{{ supervisor_user }}"
    group: "{{ common_web_user }}"
    mode: 0744
  tags:
    - devstack
    - devstack:install

- name: setup the credentials env file
  template:
    src: "./{{ credentials_home }}/{{ credentials_service_name }}_env.j2"
    dest: "{{ credentials_home }}/credentials_env"
    owner: "{{ credentials_user }}"
    group: "{{ credentials_user }}"
    mode: 0644
  tags:
    - install
    - install:configuration

- name: enable supervisor script
  file:
    src: "{{ supervisor_available_dir }}/{{ credentials_service_name }}.conf"
    dest: "{{ supervisor_cfg_dir }}/{{ credentials_service_name }}.conf"
    state: link
    force: yes
  when: not disable_edx_services
  tags:
    - install
    - install:configuration

- name: update supervisor configuration
  command: "{{ supervisor_ctl }} -c {{ supervisor_cfg }} update"
  when: not disable_edx_services
  tags:
    - manage
    - manage:start

- name: create symlinks from the venv bin dir
  file:
    src: "{{ credentials_venv_dir }}/bin/{{ item }}"
    dest: "{{ COMMON_BIN_DIR }}/{{ item.split('.')[0] }}.credentials"
    state: link
  with_items:
    - python
    - pip
    - django-admin.py
  tags:
    - install
    - install:app-requirements

- name: create symlinks from the repo dir
  file:
    src: "{{ credentials_code_dir }}/{{ item }}"
    dest: "{{ COMMON_BIN_DIR }}/{{ item.split('.')[0] }}.credentials"
    state: link
  with_items:
    - manage.py
  tags:
    - install
    - install:app-requirements

- name: run r.js optimizer
  shell: >
    chdir={{ cerdentials_code_dir }}
    . {{ cerdentials_nodeenv_bin }}/activate && {{ cerdentials_node_bin }}/r.js -o build.js
  sudo_user: "{{ cerdentials_user }}"
  when: not devstack

- name: run collectstatic
  command: make static
  args:
    chdir: "{{ credentials_code_dir }}"
  sudo_user: "{{ credentials_user }}"
  environment: "{{ credentials_environment }}"
  tags:
    - assets
    - assets:gather

- name: restart the application
  supervisorctl: 
    state: restarted
    supervisorctl_path: "{{ supervisor_ctl }}"
    config: "{{ supervisor_cfg }}"
    name: "{{ credentials_service_name }}"
  when: not disable_edx_services
  sudo_user: "{{ supervisor_service_user }}"
  tags:
    - manage
    - manage:start

- name: Copying nginx configs for credentials
  template: >
    src=edx/app/nginx/sites-available/credentials.j2
    dest={{ nginx_sites_available_dir }}/credentials
    owner=root group={{ common_web_user }} mode=0640
  notify: reload nginx
  tags:
    - install
    - install:vhosts

- name: Creating nginx config links for credentials
  file: >
    src={{ nginx_sites_available_dir }}/credentials
    dest={{ nginx_sites_enabled_dir }}/credentials
    state=link owner=root group=root
  notify: reload nginx
  tags:
    - install
    - install:vhosts
