- name: Deploy Credentials
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    serial_count: 1
  serial: "{{ serial_count }}"
  roles:
    - nginx
    - role: credentials
      nginx_default_sites:
        - credentials
