---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Role includes for role credentials
# 
# Example:
#
# dependencies:
#   - {
#   role: my_role 
#   my_role_var0: "foo"
#   my_role_var1: "bar"
# }
dependencies:
  - role: edx_service
    edx_service_name: "{{ credentials_service_name }}"
    edx_service_config: "{{ CREDENTIALS_SERVICE_CONFIG }}"
    edx_service_repos: "{{ CREDENTIALS_REPOS }}"
    edx_service_user: "{{ credentials_user }}"
    edx_service_home: "{{ credentials_home }}"
    edx_service_packages:
      debian: "{{ credentials_debian_pkgs }}"
      redhat: "{{ credentials_redhat_pkgs }}"
  - supervisor
