---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role credentials
# 
CREDENTIALS_GIT_IDENTITY: !!null

# depends upon Newrelic being enabled via COMMON_ENABLE_NEWRELIC
# and a key being provided via NEWRELIC_LICENSE_KEY
CREDENTIALS_NEWRELIC_APPNAME: "{{ COMMON_ENVIRONMENT }}-{{ COMMON_DEPLOYMENT }}-{{ credentials_service_name }}"
CREDENTIALS_PIP_EXTRA_ARGS: "-i {{ COMMON_PYPI_MIRROR_URL }}"
CREDENTIALS_NGINX_PORT: 18150
CREDENTIALS_SSL_NGINX_PORT: 48150

CREDENTIALS_DEFAULT_DB_NAME: 'credentials'
CREDENTIALS_MYSQL: 'localhost'
# MySQL usernames are limited to 16 characters
CREDENTIALS_MYSQL_USER: 'credentials001'
CREDENTIALS_MYSQL_PASSWORD: 'password'

CREDENTIALS_DATABASES:
  # rw user
  default:
    ENGINE: 'django.db.backends.mysql'
    NAME: '{{ CREDENTIALS_DEFAULT_DB_NAME }}'
    USER: '{{ CREDENTIALS_MYSQL_USER }}'
    PASSWORD: '{{ CREDENTIALS_MYSQL_PASSWORD }}'
    HOST: '{{ CREDENTIALS_MYSQL }}'
    PORT: '3306'
    ATOMIC_REQUESTS: true
    CONN_MAX_AGE: 60

CREDENTIALS_DB_ADMIN_USER: 'root'
CREDENTIALS_DB_ADMIN_PASSWORD: ''

CREDENTIALS_MEMCACHE: [ 'memcache' ]

CREDENTIALS_CACHES:
  default:
    BACKEND:  'django.core.cache.backends.memcached.MemcachedCache'
    KEY_PREFIX: 'default'
    LOCATION: '{{ CREDENTIALS_MEMCACHE }}'

CREDENTIALS_VERSION: "master"
CREDENTIALS_DJANGO_SETTINGS_MODULE: "credentials.settings.production"
CREDENTIALS_URL_ROOT: 'http://127.0.0.1:18150'
CREDENTIALS_OAUTH_URL_ROOT: 'http://127.0.0.1:8000'

CREDENTIALS_SECRET_KEY: 'Your secret key here'
CREDENTIALS_TIME_ZONE: 'UTC'
CREDENTIALS_LANGUAGE_CODE: 'en-us'

# Used to automatically configure OAuth2 Client
CREDENTIALS_SOCIAL_AUTH_EDX_OIDC_KEY : 'credentials-key'
CREDENTIALS_SOCIAL_AUTH_EDX_OIDC_SECRET : 'credentials-secret'
CREDENTIALS_SOCIAL_AUTH_REDIRECT_IS_HTTPS: false

CREDENTIALS_PLATFORM_NAME: 'Your Platform Name Here'

CREDENTIALS_SERVICE_CONFIG:
  SECRET_KEY: '{{ CREDENTIALS_SECRET_KEY }}'
  TIME_ZONE: '{{ CREDENTIALS_TIME_ZONE }}'
  LANGUAGE_CODE: '{{ CREDENTIALS_LANGUAGE_CODE }}'

  SOCIAL_AUTH_EDX_OIDC_KEY: '{{ CREDENTIALS_SOCIAL_AUTH_EDX_OIDC_KEY }}'
  SOCIAL_AUTH_EDX_OIDC_SECRET: '{{ CREDENTIALS_SOCIAL_AUTH_EDX_OIDC_SECRET }}'
  SOCIAL_AUTH_EDX_OIDC_ID_TOKEN_DECRYPTION_KEY: '{{ CREDENTIALS_SOCIAL_AUTH_EDX_OIDC_SECRET }}'
  SOCIAL_AUTH_EDX_OIDC_URL_ROOT: '{{ CREDENTIALS_OAUTH_URL_ROOT }}/oauth2'
  SOCIAL_AUTH_REDIRECT_IS_HTTPS: '{{ CREDENTIALS_SOCIAL_AUTH_REDIRECT_IS_HTTPS }}'

  STATIC_ROOT: "{{ COMMON_DATA_DIR }}/{{ credentials_service_name }}/staticfiles"
  # db config
  DATABASE_OPTIONS:
    connect_timeout: 10
  DATABASES: '{{ CREDENTIALS_DATABASES }}'

  PLATFORM_NAME: '{{ CREDENTIALS_PLATFORM_NAME }}'


CREDENTIALS_REPOS:
  - PROTOCOL: "{{ COMMON_GIT_PROTOCOL }}"
    DOMAIN: "{{ COMMON_GIT_MIRROR }}"
    PATH: "{{ COMMON_GIT_PATH }}"
    REPO: credentials.git
    VERSION: "{{ CREDENTIALS_VERSION }}"
    DESTINATION: "{{ credentials_code_dir }}"
    SSH_KEY: "{{ CREDENTIALS_GIT_IDENTITY }}"


CREDENTIALS_GUNICORN_WORKERS: "2"
CREDENTIALS_GUNICORN_EXTRA: ""
CREDENTIALS_GUNICORN_EXTRA_CONF: ""
CREDENTIALS_GUNICORN_WORKER_CLASS: "gevent"

CREDENTIALS_HOSTNAME: '~^((stage|prod)-)?credentials.*'

nginx_credentials_gunicorn_hosts:
  - 127.0.0.1

#
# vars are namespace with the module name.
#
credentials_role_name: credentials
credentials_venv_dir: "{{ credentials_home }}/venvs/{{ credentials_service_name }}"

credentials_environment:
  DJANGO_SETTINGS_MODULE: "{{ CREDENTIALS_DJANGO_SETTINGS_MODULE }}"
  CREDENTIALS_CFG: "{{ COMMON_CFG_DIR }}/{{ credentials_service_name }}.yml"
  PATH: "{{ credentials_venv_dir }}/bin:{{ ansible_env.PATH }}"

credentials_migration_environment:
  DJANGO_SETTINGS_MODULE: "{{ CREDENTIALS_DJANGO_SETTINGS_MODULE }}"
  CREDENTIALS_CFG: "{{ COMMON_CFG_DIR }}/{{ credentials_service_name }}.yml"
  PATH: "{{ credentials_venv_dir }}/bin:{{ ansible_env.PATH }}"
  DB_MIGRATION_USER: "{{ COMMON_MYSQL_MIGRATE_USER }}"
  DB_MIGRATION_PASS: "{{ COMMON_MYSQL_MIGRATE_PASS }}"

credentials_service_name: "credentials"
credentials_user: "{{ credentials_service_name }}"
credentials_home: "{{ COMMON_APP_DIR }}/{{ credentials_service_name }}"
credentials_code_dir: "{{ credentials_home }}/{{ credentials_service_name }}"

credentials_gunicorn_host: "127.0.0.1"
credentials_gunicorn_port: 8150
credentials_gunicorn_timeout: 300

credentials_log_dir: "{{ COMMON_LOG_DIR }}/{{ credentials_service_name }}"

#
# OS packages
#

credentials_debian_pkgs:
  - libmysqlclient-dev
  - libssl-dev

credentials_redhat_pkgs: []
